PETBlog/blog/accounts/urls.py
from django.urls import path
from .views import (
    RegisterView,
    ProfileView,
    UserListView,
    PostListView,
    UserRemoveView,
    UserChangeRoleView,
    LikedPostsView,
    ProfileEditView,
)
from django.contrib.auth import views as auth_views

"""

register/, login/, logout/ 
- For registration, authorization.

profile/<int:pk>/ 
- A user's profile page containing information about the user and a list of their publications.

remove-user/<int:pk>/ 
- To remove a user (administrative tool).

change-user-role/<int:pk>/ 
- To change the user/admin role (administrative tool).

users/
- Page with a list of all users (administrative tool).

admin-post-list/
- Page with a list of publications (administrative tool).

"""


urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile-edit'),

    path('remove-user/<int:pk>/', UserRemoveView.as_view(), name='remove-user'),
    path('change-user-role/<int:pk>/', UserChangeRoleView.as_view(), name='change-user-role'),

    path('users/', UserListView.as_view(), name='user-list'),
    path('admin-post-list/', PostListView.as_view(), name='admin-post-list'),

    path('user-like-post-list/', LikedPostsView.as_view(), name='user-like-post-list'),



]

PETBlog/blog/api/home/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    PostListAPIView,
    PostDetailAPIView,
    PostCreateAPIView,
    PostRemoveAPIView,
    PostUpdateAPIView,
    PostStatusChangeAPIView,
    PostLikeAPIView,
    CommentCreateAPIView,
    CommentRemoveAPIView,
    PostSearchAPIView,
    CategoryAPIView,
)

urlpatterns = [
    path('post-list/', PostListAPIView.as_view(), name='api-post-list'),
    path('post/<int:pk>/', PostDetailAPIView.as_view(), name='api-post-detail'),
    path('posts/create/', PostCreateAPIView.as_view(), name='api-post-create'),
    path('posts/remove/<int:pk>/', PostRemoveAPIView.as_view(), name='api-post-remove'),
    path('posts/update/<int:pk>/', PostUpdateAPIView.as_view(), name='api-post-update'),
    path('posts/status-change/<int:pk>/', PostStatusChangeAPIView.as_view(), name='api-post-status-change'),
    path('post-like/<int:pk>/', PostLikeAPIView.as_view(), name='api-post-like'),
    path('comment-create/<int:pk>/', CommentCreateAPIView.as_view(), name='api-comment-create'),
    path('comment-remove/<int:pk>/', CommentRemoveAPIView.as_view(), name='api-comment-remove'),
    path('post-search/', PostSearchAPIView.as_view(), name='api-post-search'),
    path('category/<int:pk>/', CategoryAPIView.as_view(), name='api-category'),

]

PETBlog/blog/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('accounts.urls')),
    path('api/home/', include('api.home.urls')),
    path('api/account/', include('api.account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PETBlog/blog/home/urls.py
from django.urls import path, include
from .views import (
    Index,
    PostDetailView,
    PostCreateView,
    RemovePostView,
    PostUpdateView,
    PostStatusChangeView,
    SearchView,
    CategoryView,
    PostLikeView,
    TopTenView,
    CommentCreateView,
    RemoveCommentView,
    CommentLikeView,
    AboutView
)
"""


- index

<int:pk>/
- Page of publication.

post_create/
- Page to create a publication.

remove_post/<pk>/
- To remove a publication.

post/<int:pk>/edit/
- Page to edit the publication.

post/<int:pk>/change_status/
- To change the status of a publication (published/hidden).

like/<int:pk>/
- To like the publication.

post/<int:pk>/comment/
- For commenting on a publication.

comment/<int:pk>/remove/
- To remove a comment.

search/
- A page with a list of the result of the publication search.

category/<pk>/
- A page with a list of all publications with a specific category.

about/
- A page with information about the project.

"""
urlpatterns = [
    path('', Index.as_view(), name='index'),

    path('<int:pk>/', PostDetailView.as_view(), name='post'),
    path('post_create/', PostCreateView.as_view(), name='post-create'),
    path('remove_post/<pk>/', RemovePostView.as_view(), name='remove-post'),
    path('post/<int:pk>/edit/', PostUpdateView.as_view(), name='post_edit'),

    path('post/<int:pk>/change_status/', PostStatusChangeView.as_view(), name='post-change-status'),
    path('like/<int:pk>/', PostLikeView.as_view(), name='post-like'),


    path('post/<int:pk>/comment/', CommentCreateView.as_view(), name='add-comment'),
    path('comment/<int:pk>/remove/', RemoveCommentView.as_view(), name='remove-comment'),
    path('like_comment/<int:pk>/', CommentLikeView.as_view(), name='like-comment'),

    path('top_ten/', TopTenView.as_view(), name='top-ten'),
    path('search/', SearchView.as_view(), name='search'),
    path('category/<pk>/', CategoryView.as_view(), name='category'),

    path('about/', AboutView.as_view(), name='about'),
]

PETBlog/blog/home/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Category(models.Model):
    """

    Model representing categories for posts.

    Fields:
        title (CharField)

    """

    title = models.CharField(
        verbose_name='title',
        max_length=255,
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    """

    Model representing a post.

    Fields:
        title (CharField)
        content (CharField)
        category (ForeignKey)
        image (ImageField)
        date (DateField)
        author (ForeignKey)
        likes (ManyToManyField)
        status (CharField) (published or hidden)

    """
    title = models.CharField(
        verbose_name='title',
        max_length=255
    )
    content = models.CharField(
        verbose_name='content',
        max_length=2048
    )
    category = models.ForeignKey(
        Category,
        verbose_name='category',
        on_delete=models.CASCADE,
        null=True
    )

    image = models.ImageField(
        upload_to='post_images/',
        null=True,
        blank=True
    )

    date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='post_like')

    STATUS_CHOICES = [
        ('published', 'Published'),
        ('hidden', 'Hidden'),
    ]

    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='published'
    )

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

    def number_of_comments(self):
        return Comment.objects.filter(post=self).count()



class Comment(models.Model):
    """

    Model representing comments on posts.

    Fields:
        post (ForeignKey)
        author (ForeignKey)
        content (TextField)
        date (DateTimeField)
        likes (ManyToManyField)
        status (CharField) (published or hidden)

    """
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    content = models.TextField(
        verbose_name='content',
        max_length=120
    )
    date = models.DateTimeField(
        auto_now_add=True
    )

    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='comment_like')

    STATUS_CHOICES = [
        ('published', 'Published'),
        ('hidden', 'Hidden'),
    ]

    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='published'
    )

    def __str__(self):
        return f'Comment by {self.author.username} on {self.post.title}'

    def number_of_likes(self):
        return self.likes.count()

PETBlog/blog/home/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    """

    Form for creating and updating a post.

    """
    class Meta:
        model = Post
        fields = ('title', 'content', 'category', 'image')

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if len(title) > 255:
            raise forms.ValidationError('Title cannot exceed 255 characters.')
        return title

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) > 2048:
            raise forms.ValidationError('Content cannot exceed 2048 characters.')
        return content


class SearchForm(forms.Form):
    """

    Form for searching posts.

    """
    query = forms.CharField(max_length=100, required=False)


class CommentForm(forms.ModelForm):
    """

    Form for creating comments on posts.

    """
    comment_content = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Comment
        fields = ('comment_content',)

PETBlog/blog/api/home/views.py
from django.urls import reverse
from rest_framework import generics
from rest_framework.generics import get_object_or_404, ListAPIView
from rest_framework.views import APIView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from home.models import Category, Post, Comment

from .serializers import (
    CategorySerializer,
    CommentSerializer,
    PostListSerializer,
    PostDetailSerializer,
    PostCreateSerializer,
    PostUpdateSerializer,
    PostStatusChangeSerializer,
    PostLikeSerializer,
    CommentCreateSerializer,
    PostSearchSerializer,
    PostCategorySerializer,
)


class PostListAPIView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer


class PostDetailAPIView(APIView):
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        serializer = PostDetailSerializer(post, context={'request': request})
        return Response(serializer.data)

    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        comment_data = request.data
        comment_data['post'] = pk
        serializer = CommentSerializer(data=comment_data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class PostCreateAPIView(generics.CreateAPIView):
    serializer_class = PostCreateSerializer

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

    def get_queryset(self):
        return Post.objects.all()


class PostRemoveAPIView(generics.DestroyAPIView):

    def get_queryset(self):
        return Post.objects.all()

    def delete(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        post = get_object_or_404(Post, pk=pk)
        user = self.request.user

        if post.author == user or user.role == 'admin':
            post.delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        else:
            return Response(status=status.HTTP_403_FORBIDDEN)


class PostUpdateAPIView(generics.UpdateAPIView):
    serializer_class = PostUpdateSerializer

    def get_queryset(self):
        return Post.objects.all()

    def get_serializer(self, *args, **kwargs):
        kwargs['context'] = self.get_serializer_context()
        return self.serializer_class(*args, **kwargs)


class PostStatusChangeAPIView(generics.UpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostStatusChangeSerializer

    def update(self, request, *args, **kwargs):
        post = self.get_object()
        user = self.request.user

        if user.role == 'admin':
            post.status = 'hidden' if post.status == 'published' else 'published'
            post.save()

            serializer = self.get_serializer(post)
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response(status=status.HTTP_403_FORBIDDEN)


class PostLikeAPIView(APIView):
    def get(self, request, pk):
        post = get_object_or_404(Post, id=pk)

        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
            liked = False
        else:
            post.likes.add(request.user)
            liked = True

        likes_count = post.likes.count()

        serializer = PostLikeSerializer(data={'liked': liked, 'likes_count': likes_count})

        if serializer.is_valid():
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CommentCreateAPIView(generics.CreateAPIView):
    serializer_class = CommentCreateSerializer

    def perform_create(self, serializer):
        pk = self.kwargs.get('pk')
        post = get_object_or_404(Post, pk=pk)
        serializer.save(post=post, author=self.request.user, status='published')

    def get_queryset(self):
        return Comment.objects.all()


class CommentRemoveAPIView(generics.DestroyAPIView):
    def get_queryset(self):
        return Comment.objects.all()

    def delete(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=self.kwargs['pk'])
        user = self.request.user

        if comment.author == user or user.role == 'admin':
            comment.delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        else:
            return Response(status=status.HTTP_403_FORBIDDEN)


class PostSearchAPIView(generics.ListAPIView):
    serializer_class = PostSearchSerializer

    def get_queryset(self):
        query = self.request.query_params.get('query', 'lo')
        return Post.objects.filter(title__icontains=query)


class CategoryAPIView(generics.ListAPIView):
    serializer_class = PostCategorySerializer

    def get_queryset(self):
        category_id = self.kwargs.get('pk')
        return Post.objects.filter(category_id=category_id)

PETBlog/blog/home/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>About PETBlog</h1>
    <p>Welcome to PETBlog - a place where we share stories, research, and a variety of interesting articles. Our blog is created to enrich you with diverse content and discuss the most relevant topics.</p>

    <h2>Our Mission</h2>
    <p>We aim to provide you with engaging, informative, and inspiring materials. Whether you're interested in technology, art, travel, or other aspects of life, we have something for everyone.</p>

    <h2>How We Work</h2>
    <p>We place great emphasis on the quality of our content. Our articles go through a rigorous editorial process to ensure that each one offers value and interest to you.</p>

    <h2>Contact Us</h2>
    <p>We value your feedback and opinions. If you have suggestions, questions, or comments, please feel free to reach out to us through our contact form.</p>

    <p>Thank you for visiting PETBlog! We hope you find something interesting and inspiring here. Happy reading!</p>
{% endblock %}

PETBlog/blog/home/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PETBlog</title>
    {% load static %}
        <link rel="icon" href= "{% static 'logo1.jpg' %}" type="image/x-icon" >
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">


    <title>PETBlog</title>
</head>

<body class=" bodyviv bg-image" style="">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<!-- --- --- header --- --- -->
{% include 'header.html'%}
<div class="container " style="min-height: calc(100vh - 70px);">

    {% block content %}


    {% endblock content %}

</div>
<!-- --- --- footer --- --- -->
<div style="height: 50px;">{% include 'footer.html'%}</div>

</body>
</html>

PETBlog/blog/home/templates/category.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
<h1>{{ category.title }}:</h1>
<!-- --- --- Post list by category --- --- -->
{% include 'post_list.html' %}
</div>
{% endblock %}

PETBlog/blog/home/templates/footer.html
<footer class="bg-dark text-light  py-3" style="position: sticky; top: 0;">
    <div class="container">
        <div class="row ">
            <div class="col-md-4 mb-3">
                <ul class="list-unstyled">
                    <li>Contact Information:</li>
                    <li>Email: tstemail@example.com</li>
                    <li>Phone: +123 456 789</li>
                </ul>

            </div>
            <div class="col-md-4 mb-3">
                <ul class="list-unstyled">
                    <li>Links:</li>
                    <li><a class="text-light" href="https://twitter.com/">X(Twitter)</a></li>
                    <li><a class="text-light" href="https://www.facebook.com">Facebook</a></li>
                    <li><a class="text-light" href="https://github.com/">GitHub</a></li>
                </ul>
            </div>
            <div class="col-md-4 mb-3">
                <ul class="list-unstyled">
                    <li><a class="text-light" href="{% url 'about' %}" >About</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

PETBlog/blog/home/templates/index.html
{% extends 'base.html' %}

{% block content %}

<!-- --- --- POST LIST --- --- -->
{% include 'post_list.html' %}

{% endblock content %}

PETBlog/blog/home/templates/post_create.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h2>Create Post</h2>
    <form class="form-group" action="{% url 'post-create' %}" id="postForm" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- --- --- TITLE --- --- -->
        <input type="text" name="title" class="form-control" placeholder="title" required maxlength="255"><br/>
        <!-- --- --- CATEGORY --- --- -->
        <label for="exampleFormControlSelect1">Category</label>
        <select name="category" class="form-control" id="exampleFormControlSelect1">
            {% for category in category_list %}
            <option class="disabled" name="{{category.title}}" value="{{category.id}}">{{category.title}}</option>
            {% endfor %}
        </select>
        <p></p>
        <!-- --- --- CONTENT --- --- -->
        <textarea rows="4" cols="50" name="content" class="form-control" placeholder="content" required maxlength="2048"></textarea><br/>
        <!-- --- --- IMAGE --- --- -->
        <div class="input-group mb-3">
          <label class="input-group-text" for="inputGroupFile01">Image</label>
          <input type="file" name="image" accept="image/*" class="form-control" id="inputGroupFile01">
        </div><br/>
        <!-- --- --- SAVE BUTTON --- --- -->
        <button class="btn btn-primary rounded-0 shadow-sm btn-block" type="submit" id="submitBtn">Save</button>

    </form>
<br/>
</div>
<!-- --- --- VALIDATION SCRIPT --- --- -->
<script>
    document.getElementById('submitBtn').addEventListener('click', function(event) {
        var title = document.querySelector('[name="title"]').value;
        var category = document.querySelector('[name="category"]').value;
        var content = document.querySelector('[name="content"]').value;

        if (!title || !category || !content) {
            alert('All fields are required!');
            return;
        }

        document.getElementById('postForm').submit();
    });
</script>
{% endblock content %}

PETBlog/blog/home/templates/post_edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-4">
  <h2>Edit Post</h2>
  <form method="post" action="{% url 'post_edit' pk=post.pk %}" id="editPostForm" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.title|as_crispy_field }}
      {{ form.category|as_crispy_field }}
    <div class="form-group">
        <label for="{{ form.content.id_for_label }}">Content</label>
        <textarea class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.html_name }}" rows="10">{{ form.content.value }}</textarea>
    </div>
    <br/>
    {{ form.image|as_crispy_field }}
    <br/>
    <button type="submit" class="btn btn-primary rounded-0 shadow-sm btn-block" id="saveChangesBtn">Save Changes</button>

  </form>
  <br/>
</div>

<!-- --- --- VALIDATION SCRIPT --- --- -->
<script>
    document.getElementById('saveChangesBtn').addEventListener('click', function(event) {
        var title = document.querySelector('[name="title"]').value;
        var category = document.querySelector('[name="category"]').value;
        var content = document.querySelector('[name="content"]').value;

        if (!title || !category || !content) {
            alert('All fields are required!');
            return;
        }

        if (title.length > 255) {
            alert('Title cannot exceed 255 characters!');
            return;
        }

        if (content.length > 2048) {
            alert('Content cannot exceed 2048 characters!');
            return;
        }

        document.getElementById('editPostForm').submit();
    });
</script>
{% endblock %}

PETBlog/blog/home/templates/post_top_ten.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
<h1>TOP 10:</h1>
<!-- --- --- POST LIST BY TOP 10 --- --- -->
{% include 'post_list.html' %}
</div>
{% endblock %}

PETBlog/blog/home/templates/search_results.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
<h1>Search Results:</h1>
<!-- --- --- POST LIST BY SEARCH RESULT --- --- -->
{% include 'post_list.html' %}
</div>
{% endblock %}